name: sports-arena

services:
  strapi:
    container_name: sports-arena-strapi-production
    image: sports-arena/strapi:latest
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.prod
    env_file:
      - path: .env
      - path: .env.docker
    environment:
      # Overrides the development value from env_file
      NODE_ENV: production
    ports:
      - "127.0.0.1:1337:1337"
    networks:
      - sports-arena
    depends_on:
      strapiDB:
        condition: service_healthy

  strapiDB:
    container_name: sports-arena-strapi-db
    image: postgres:18-alpine
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - type: volume
        source: strapi-db-data
        target: /var/lib/postgresql
    networks:
      - sports-arena
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DATABASE_USERNAME} -d ${DATABASE_NAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  strapi-db-data:
    name: sports-arena-db-data

networks:
  sports-arena:
    name: sports-arena-network
    driver: bridge
